package.json, pnpm-lock.yaml, src/components/Input.tsx, src/components/Navbar.tsx, src/components/Tag.tsx, src/pages/_app.tsx, src/pages/dashboard.tsx, src/styles/globals.css
=> feat: add basic layout for dashboard

prisma/schema.prisma
- Added timeslots table for participants
- Dropped unique constraint from Event
=> feat: added timeslots table

prisma/schema.prisma
Note that joinCode is a length-6 string composed of integers.
=> Add joinCode in schema in Event table

pnpm-lock.yaml, src/pages/dashboard.tsx, src/pages/event/[id].tsx
NOTE: mobile size not optimized
=> feat: event page sign-in block

package.json, pnpm-lock.yaml, src/components/DateSelect.tsx, src/pages/dashboard.tsx
Add a date selector so that the user can select days for an event.
=> feat: calendar date selector

src/components/DateSelect.tsx, src/components/Input.tsx, src/components/Navbar.tsx, src/components/Tag.tsx, src/pages/dashboard.tsx, src/pages/event/[id].tsx, src/pages/index.tsx, src/styles/globals.css, src/utils/timezone.ts
=> feat: timezone selector & visual enhancements

src/components/Input.tsx, src/pages/dashboard.tsx
Add timespan selector to dashboard.
=> feat: timespan selector

src/components/Navbar.tsx, src/pages/dashboard.tsx, src/pages/index.tsx
=> fix: misc fixes on Navbar & Dashboard authriozation

src/pages/dashboard.tsx, src/pages/event/[id].tsx
=> chore: remove participant count

src/components/section/Navbar.tsx, src/pages/dashboard.tsx
=> feat: responsive design

.env.example, .github/workflows/main.yml, README.md
=> chore: all kinds of fixes

.husky/pre-commit, package.json, pnpm-lock.yaml
Husky is a local pre-commit hook that will be triggered everything you make a commit locally. 
In this PR I've set it to run `pnpm run lint` every time you commit, if lint fails, the commit fails as well.
Husky is being used in most major repos including webpack, angular, rollup and a lot more. So I thought this would be a nice addition to this repo as well.
[Link to Husky GitHub repo](https://github.com/typicode/husky)
=> CI: Added husky pre-commit hooks

src/components/section/Dialog.tsx, src/pages/event/[id].tsx, src/server/api/routers/participateRoute.ts
- Fixes #53 
Added edit functionality in `edit` button
=> feat: delete participants if owner

prisma/schema.prisma, src/server/api/routers/eventRoute.ts
Change field `address` to `timeZone`. The development database has been updated accordingly using `prisma db push`. Merge this as soon as possible to prevent conflicts.
=> feat!: update db schema and related routes

src/components/section/Dialog.tsx, src/pages/event/[id].tsx, src/server/api/routers/participateRoute.ts
Add participants leaving UI
Realize removing participants from database.
=> Realize participants leaving

src/components/section/NewEventCard.tsx, src/utils/api-hooks.ts
=> fix: join existing button loading behavior

src/components/section/AvailabilityZone.tsx, src/components/section/EventInfoHeader.tsx, src/components/section/EventList.tsx, src/components/section/OperationCard.tsx, src/components/ui/Button.tsx, src/components/ui/ScreenLoading.tsx, src/components/ui/TimeSlotParticipantsPanel.tsx, src/components/ui/TimeslotGrid.tsx, src/components/ui/TimeslotSavePanel.tsx, src/pages/dashboard.tsx, src/pages/event/[id].tsx, src/pages/index.tsx, src/styles/globals.css
Checklist:
Some of the above need to be tested in production build, so please run `build` and then `start` to test them correctly!
=> feat: better loading behavior overall

src/app-data.ts, src/components/section/EventInfoHeader.tsx, src/components/section/Footer.tsx, src/components/section/Navbar.tsx, src/components/section/OperationCard.tsx, src/pages/dashboard.tsx, src/pages/event/[id].tsx, src/pages/index.tsx
Add a footer with a link to this GitHub repository and add a bottom border to the navbar. Fixes #55.
=> feat: add footer & update navbar style

README.md
- Added star history graph
- Tidied up markdown, removed in-line html and use proper markdown syntax for putting images.
=> doc: updated README

.github/workflows/main.yml
This is here to resolve the previous PR issue on #87
=> fix?:update github action with `--no-frozen-lockfile`

src/components/section/AvailabilityZone.tsx, src/components/section/NewEventCard.tsx, src/components/section/OperationCard.tsx, src/components/ui/StyleScheduleSelector.tsx, src/components/ui/TimeSlotParticipantsPanel.tsx, src/utils/date-utils.ts, tailwind.config.cjs
=> fix: tabs behavior & participant filter logic and display & refactor
